import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the src/ directory
*/
`;

const prod = process.argv[2] === "production";

const pluginContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

const rendererContext = await esbuild.context({
	entryPoints: ["src/renderer/App.tsx"],
	bundle: true,
	format: "iife",
	globalName: "AgentSwarmApp",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	outfile: "src/renderer/app.bundle.js",
	minify: prod,
});

if (prod) {
	await pluginContext.rebuild();
	await rendererContext.rebuild();
	process.exit(0);
} else {
	await pluginContext.watch();
	await rendererContext.watch();
}
